/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as TeacherRouteRouteImport } from './routes/teacher/route'
import { Route as StudentRouteRouteImport } from './routes/student/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher/index'
import { Route as StudentIndexRouteImport } from './routes/student/index'
import { Route as TeacherStudentsRouteImport } from './routes/teacher/students'
import { Route as TeacherReportsRouteImport } from './routes/teacher/reports'
import { Route as TeacherCoursesRouteImport } from './routes/teacher/courses'
import { Route as TeacherCalendarRouteImport } from './routes/teacher/calendar'
import { Route as StudentResourcesRouteImport } from './routes/student/resources'
import { Route as StudentGradesRouteImport } from './routes/student/grades'
import { Route as StudentAssignmentsRouteImport } from './routes/student/assignments'
import { Route as TeacherFeedbackCourseIdRouteImport } from './routes/teacher/feedback.$courseId'
import { Route as TeacherCoursesCourseIdRouteImport } from './routes/teacher/courses/$courseId'
import { Route as StudentFeedbackCourseIdRouteImport } from './routes/student/feedback.$courseId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRouteRoute = TeacherRouteRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRouteRoute = StudentRouteRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRouteRoute,
} as any)
const TeacherStudentsRoute = TeacherStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherReportsRoute = TeacherReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherCoursesRoute = TeacherCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherCalendarRoute = TeacherCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const StudentResourcesRoute = StudentResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentGradesRoute = StudentGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => StudentRouteRoute,
} as any)
const StudentAssignmentsRoute = StudentAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => StudentRouteRoute,
} as any)
const TeacherFeedbackCourseIdRoute = TeacherFeedbackCourseIdRouteImport.update({
  id: '/feedback/$courseId',
  path: '/feedback/$courseId',
  getParentRoute: () => TeacherRouteRoute,
} as any)
const TeacherCoursesCourseIdRoute = TeacherCoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => TeacherCoursesRoute,
} as any)
const StudentFeedbackCourseIdRoute = StudentFeedbackCourseIdRouteImport.update({
  id: '/feedback/$courseId',
  path: '/feedback/$courseId',
  getParentRoute: () => StudentRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/student': typeof StudentRouteRouteWithChildren
  '/teacher': typeof TeacherRouteRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/resources': typeof StudentResourcesRoute
  '/teacher/calendar': typeof TeacherCalendarRoute
  '/teacher/courses': typeof TeacherCoursesRouteWithChildren
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/student/feedback/$courseId': typeof StudentFeedbackCourseIdRoute
  '/teacher/courses/$courseId': typeof TeacherCoursesCourseIdRoute
  '/teacher/feedback/$courseId': typeof TeacherFeedbackCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/resources': typeof StudentResourcesRoute
  '/teacher/calendar': typeof TeacherCalendarRoute
  '/teacher/courses': typeof TeacherCoursesRouteWithChildren
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/student/feedback/$courseId': typeof StudentFeedbackCourseIdRoute
  '/teacher/courses/$courseId': typeof TeacherCoursesCourseIdRoute
  '/teacher/feedback/$courseId': typeof TeacherFeedbackCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/student': typeof StudentRouteRouteWithChildren
  '/teacher': typeof TeacherRouteRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/student/assignments': typeof StudentAssignmentsRoute
  '/student/grades': typeof StudentGradesRoute
  '/student/resources': typeof StudentResourcesRoute
  '/teacher/calendar': typeof TeacherCalendarRoute
  '/teacher/courses': typeof TeacherCoursesRouteWithChildren
  '/teacher/reports': typeof TeacherReportsRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/student/feedback/$courseId': typeof StudentFeedbackCourseIdRoute
  '/teacher/courses/$courseId': typeof TeacherCoursesCourseIdRoute
  '/teacher/feedback/$courseId': typeof TeacherFeedbackCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/student'
    | '/teacher'
    | '/landing'
    | '/login'
    | '/student/assignments'
    | '/student/grades'
    | '/student/resources'
    | '/teacher/calendar'
    | '/teacher/courses'
    | '/teacher/reports'
    | '/teacher/students'
    | '/student/'
    | '/teacher/'
    | '/student/feedback/$courseId'
    | '/teacher/courses/$courseId'
    | '/teacher/feedback/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/landing'
    | '/login'
    | '/student/assignments'
    | '/student/grades'
    | '/student/resources'
    | '/teacher/calendar'
    | '/teacher/courses'
    | '/teacher/reports'
    | '/teacher/students'
    | '/student'
    | '/teacher'
    | '/student/feedback/$courseId'
    | '/teacher/courses/$courseId'
    | '/teacher/feedback/$courseId'
  id:
    | '__root__'
    | '/'
    | '/student'
    | '/teacher'
    | '/landing'
    | '/login'
    | '/student/assignments'
    | '/student/grades'
    | '/student/resources'
    | '/teacher/calendar'
    | '/teacher/courses'
    | '/teacher/reports'
    | '/teacher/students'
    | '/student/'
    | '/teacher/'
    | '/student/feedback/$courseId'
    | '/teacher/courses/$courseId'
    | '/teacher/feedback/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudentRouteRoute: typeof StudentRouteRouteWithChildren
  TeacherRouteRoute: typeof TeacherRouteRouteWithChildren
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/teacher/students': {
      id: '/teacher/students'
      path: '/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof TeacherStudentsRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/reports': {
      id: '/teacher/reports'
      path: '/reports'
      fullPath: '/teacher/reports'
      preLoaderRoute: typeof TeacherReportsRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/courses': {
      id: '/teacher/courses'
      path: '/courses'
      fullPath: '/teacher/courses'
      preLoaderRoute: typeof TeacherCoursesRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/calendar': {
      id: '/teacher/calendar'
      path: '/calendar'
      fullPath: '/teacher/calendar'
      preLoaderRoute: typeof TeacherCalendarRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/student/resources': {
      id: '/student/resources'
      path: '/resources'
      fullPath: '/student/resources'
      preLoaderRoute: typeof StudentResourcesRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/grades': {
      id: '/student/grades'
      path: '/grades'
      fullPath: '/student/grades'
      preLoaderRoute: typeof StudentGradesRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/student/assignments': {
      id: '/student/assignments'
      path: '/assignments'
      fullPath: '/student/assignments'
      preLoaderRoute: typeof StudentAssignmentsRouteImport
      parentRoute: typeof StudentRouteRoute
    }
    '/teacher/feedback/$courseId': {
      id: '/teacher/feedback/$courseId'
      path: '/feedback/$courseId'
      fullPath: '/teacher/feedback/$courseId'
      preLoaderRoute: typeof TeacherFeedbackCourseIdRouteImport
      parentRoute: typeof TeacherRouteRoute
    }
    '/teacher/courses/$courseId': {
      id: '/teacher/courses/$courseId'
      path: '/$courseId'
      fullPath: '/teacher/courses/$courseId'
      preLoaderRoute: typeof TeacherCoursesCourseIdRouteImport
      parentRoute: typeof TeacherCoursesRoute
    }
    '/student/feedback/$courseId': {
      id: '/student/feedback/$courseId'
      path: '/feedback/$courseId'
      fullPath: '/student/feedback/$courseId'
      preLoaderRoute: typeof StudentFeedbackCourseIdRouteImport
      parentRoute: typeof StudentRouteRoute
    }
  }
}

interface StudentRouteRouteChildren {
  StudentAssignmentsRoute: typeof StudentAssignmentsRoute
  StudentGradesRoute: typeof StudentGradesRoute
  StudentResourcesRoute: typeof StudentResourcesRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentFeedbackCourseIdRoute: typeof StudentFeedbackCourseIdRoute
}

const StudentRouteRouteChildren: StudentRouteRouteChildren = {
  StudentAssignmentsRoute: StudentAssignmentsRoute,
  StudentGradesRoute: StudentGradesRoute,
  StudentResourcesRoute: StudentResourcesRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentFeedbackCourseIdRoute: StudentFeedbackCourseIdRoute,
}

const StudentRouteRouteWithChildren = StudentRouteRoute._addFileChildren(
  StudentRouteRouteChildren,
)

interface TeacherCoursesRouteChildren {
  TeacherCoursesCourseIdRoute: typeof TeacherCoursesCourseIdRoute
}

const TeacherCoursesRouteChildren: TeacherCoursesRouteChildren = {
  TeacherCoursesCourseIdRoute: TeacherCoursesCourseIdRoute,
}

const TeacherCoursesRouteWithChildren = TeacherCoursesRoute._addFileChildren(
  TeacherCoursesRouteChildren,
)

interface TeacherRouteRouteChildren {
  TeacherCalendarRoute: typeof TeacherCalendarRoute
  TeacherCoursesRoute: typeof TeacherCoursesRouteWithChildren
  TeacherReportsRoute: typeof TeacherReportsRoute
  TeacherStudentsRoute: typeof TeacherStudentsRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  TeacherFeedbackCourseIdRoute: typeof TeacherFeedbackCourseIdRoute
}

const TeacherRouteRouteChildren: TeacherRouteRouteChildren = {
  TeacherCalendarRoute: TeacherCalendarRoute,
  TeacherCoursesRoute: TeacherCoursesRouteWithChildren,
  TeacherReportsRoute: TeacherReportsRoute,
  TeacherStudentsRoute: TeacherStudentsRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  TeacherFeedbackCourseIdRoute: TeacherFeedbackCourseIdRoute,
}

const TeacherRouteRouteWithChildren = TeacherRouteRoute._addFileChildren(
  TeacherRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudentRouteRoute: StudentRouteRouteWithChildren,
  TeacherRouteRoute: TeacherRouteRouteWithChildren,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
