/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as appCoursesRouteImport } from './routes/(app)/courses'
import { Route as appTeacherRouteRouteImport } from './routes/(app)/teacher/route'
import { Route as appStudentRouteRouteImport } from './routes/(app)/student/route'
import { Route as appTeacherIndexRouteImport } from './routes/(app)/teacher/index'
import { Route as appStudentIndexRouteImport } from './routes/(app)/student/index'
import { Route as appCoursesIndexRouteImport } from './routes/(app)/courses.index'
import { Route as appTeacherSupportRouteImport } from './routes/(app)/teacher/support'
import { Route as appTeacherStudentsRouteImport } from './routes/(app)/teacher/students'
import { Route as appTeacherSettingsRouteImport } from './routes/(app)/teacher/settings'
import { Route as appTeacherReportsRouteImport } from './routes/(app)/teacher/reports'
import { Route as appTeacherEnrollmentsRouteImport } from './routes/(app)/teacher/enrollments'
import { Route as appTeacherCoursesRouteImport } from './routes/(app)/teacher/courses'
import { Route as appTeacherCalendarRouteImport } from './routes/(app)/teacher/calendar'
import { Route as appStudentSupportRouteImport } from './routes/(app)/student/support'
import { Route as appStudentSettingsRouteImport } from './routes/(app)/student/settings'
import { Route as appStudentScheduleRouteImport } from './routes/(app)/student/schedule'
import { Route as appStudentResourcesRouteImport } from './routes/(app)/student/resources'
import { Route as appStudentMessagesRouteImport } from './routes/(app)/student/messages'
import { Route as appStudentGradesRouteImport } from './routes/(app)/student/grades'
import { Route as appStudentEnrollmentsRouteImport } from './routes/(app)/student/enrollments'
import { Route as appStudentAssignmentsRouteImport } from './routes/(app)/student/assignments'
import { Route as appCoursesCourseIdRouteImport } from './routes/(app)/courses.$courseId'
import { Route as appTeacherCoursesIndexRouteImport } from './routes/(app)/teacher/courses.index'
import { Route as appTeacherFeedbackCourseIdRouteImport } from './routes/(app)/teacher/feedback.$courseId'
import { Route as appTeacherCoursesCourseIdRouteImport } from './routes/(app)/teacher/courses.$courseId'
import { Route as appStudentFeedbackCourseIdRouteImport } from './routes/(app)/student/feedback.$courseId'
import { Route as appStudentCoursesCourseIdRouteImport } from './routes/(app)/student/courses.$courseId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appCoursesRoute = appCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => appRouteRoute,
} as any)
const appTeacherRouteRoute = appTeacherRouteRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => appRouteRoute,
} as any)
const appStudentRouteRoute = appStudentRouteRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => appRouteRoute,
} as any)
const appTeacherIndexRoute = appTeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appTeacherRouteRoute,
} as any)
const appStudentIndexRoute = appStudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appStudentRouteRoute,
} as any)
const appCoursesIndexRoute = appCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appCoursesRoute,
} as any)
const appTeacherSupportRoute = appTeacherSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => appTeacherRouteRoute,
} as any)
const appTeacherStudentsRoute = appTeacherStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => appTeacherRouteRoute,
} as any)
const appTeacherSettingsRoute = appTeacherSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appTeacherRouteRoute,
} as any)
const appTeacherReportsRoute = appTeacherReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => appTeacherRouteRoute,
} as any)
const appTeacherEnrollmentsRoute = appTeacherEnrollmentsRouteImport.update({
  id: '/enrollments',
  path: '/enrollments',
  getParentRoute: () => appTeacherRouteRoute,
} as any)
const appTeacherCoursesRoute = appTeacherCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => appTeacherRouteRoute,
} as any)
const appTeacherCalendarRoute = appTeacherCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => appTeacherRouteRoute,
} as any)
const appStudentSupportRoute = appStudentSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => appStudentRouteRoute,
} as any)
const appStudentSettingsRoute = appStudentSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appStudentRouteRoute,
} as any)
const appStudentScheduleRoute = appStudentScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => appStudentRouteRoute,
} as any)
const appStudentResourcesRoute = appStudentResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => appStudentRouteRoute,
} as any)
const appStudentMessagesRoute = appStudentMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => appStudentRouteRoute,
} as any)
const appStudentGradesRoute = appStudentGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => appStudentRouteRoute,
} as any)
const appStudentEnrollmentsRoute = appStudentEnrollmentsRouteImport.update({
  id: '/enrollments',
  path: '/enrollments',
  getParentRoute: () => appStudentRouteRoute,
} as any)
const appStudentAssignmentsRoute = appStudentAssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => appStudentRouteRoute,
} as any)
const appCoursesCourseIdRoute = appCoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => appCoursesRoute,
} as any)
const appTeacherCoursesIndexRoute = appTeacherCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appTeacherCoursesRoute,
} as any)
const appTeacherFeedbackCourseIdRoute =
  appTeacherFeedbackCourseIdRouteImport.update({
    id: '/feedback/$courseId',
    path: '/feedback/$courseId',
    getParentRoute: () => appTeacherRouteRoute,
  } as any)
const appTeacherCoursesCourseIdRoute =
  appTeacherCoursesCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => appTeacherCoursesRoute,
  } as any)
const appStudentFeedbackCourseIdRoute =
  appStudentFeedbackCourseIdRouteImport.update({
    id: '/feedback/$courseId',
    path: '/feedback/$courseId',
    getParentRoute: () => appStudentRouteRoute,
  } as any)
const appStudentCoursesCourseIdRoute =
  appStudentCoursesCourseIdRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => appStudentRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/student': typeof appStudentRouteRouteWithChildren
  '/teacher': typeof appTeacherRouteRouteWithChildren
  '/courses': typeof appCoursesRouteWithChildren
  '/courses/$courseId': typeof appCoursesCourseIdRoute
  '/student/assignments': typeof appStudentAssignmentsRoute
  '/student/enrollments': typeof appStudentEnrollmentsRoute
  '/student/grades': typeof appStudentGradesRoute
  '/student/messages': typeof appStudentMessagesRoute
  '/student/resources': typeof appStudentResourcesRoute
  '/student/schedule': typeof appStudentScheduleRoute
  '/student/settings': typeof appStudentSettingsRoute
  '/student/support': typeof appStudentSupportRoute
  '/teacher/calendar': typeof appTeacherCalendarRoute
  '/teacher/courses': typeof appTeacherCoursesRouteWithChildren
  '/teacher/enrollments': typeof appTeacherEnrollmentsRoute
  '/teacher/reports': typeof appTeacherReportsRoute
  '/teacher/settings': typeof appTeacherSettingsRoute
  '/teacher/students': typeof appTeacherStudentsRoute
  '/teacher/support': typeof appTeacherSupportRoute
  '/courses/': typeof appCoursesIndexRoute
  '/student/': typeof appStudentIndexRoute
  '/teacher/': typeof appTeacherIndexRoute
  '/student/courses/$courseId': typeof appStudentCoursesCourseIdRoute
  '/student/feedback/$courseId': typeof appStudentFeedbackCourseIdRoute
  '/teacher/courses/$courseId': typeof appTeacherCoursesCourseIdRoute
  '/teacher/feedback/$courseId': typeof appTeacherFeedbackCourseIdRoute
  '/teacher/courses/': typeof appTeacherCoursesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/courses/$courseId': typeof appCoursesCourseIdRoute
  '/student/assignments': typeof appStudentAssignmentsRoute
  '/student/enrollments': typeof appStudentEnrollmentsRoute
  '/student/grades': typeof appStudentGradesRoute
  '/student/messages': typeof appStudentMessagesRoute
  '/student/resources': typeof appStudentResourcesRoute
  '/student/schedule': typeof appStudentScheduleRoute
  '/student/settings': typeof appStudentSettingsRoute
  '/student/support': typeof appStudentSupportRoute
  '/teacher/calendar': typeof appTeacherCalendarRoute
  '/teacher/enrollments': typeof appTeacherEnrollmentsRoute
  '/teacher/reports': typeof appTeacherReportsRoute
  '/teacher/settings': typeof appTeacherSettingsRoute
  '/teacher/students': typeof appTeacherStudentsRoute
  '/teacher/support': typeof appTeacherSupportRoute
  '/courses': typeof appCoursesIndexRoute
  '/student': typeof appStudentIndexRoute
  '/teacher': typeof appTeacherIndexRoute
  '/student/courses/$courseId': typeof appStudentCoursesCourseIdRoute
  '/student/feedback/$courseId': typeof appStudentFeedbackCourseIdRoute
  '/teacher/courses/$courseId': typeof appTeacherCoursesCourseIdRoute
  '/teacher/feedback/$courseId': typeof appTeacherFeedbackCourseIdRoute
  '/teacher/courses': typeof appTeacherCoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/(app)/student': typeof appStudentRouteRouteWithChildren
  '/(app)/teacher': typeof appTeacherRouteRouteWithChildren
  '/(app)/courses': typeof appCoursesRouteWithChildren
  '/(app)/courses/$courseId': typeof appCoursesCourseIdRoute
  '/(app)/student/assignments': typeof appStudentAssignmentsRoute
  '/(app)/student/enrollments': typeof appStudentEnrollmentsRoute
  '/(app)/student/grades': typeof appStudentGradesRoute
  '/(app)/student/messages': typeof appStudentMessagesRoute
  '/(app)/student/resources': typeof appStudentResourcesRoute
  '/(app)/student/schedule': typeof appStudentScheduleRoute
  '/(app)/student/settings': typeof appStudentSettingsRoute
  '/(app)/student/support': typeof appStudentSupportRoute
  '/(app)/teacher/calendar': typeof appTeacherCalendarRoute
  '/(app)/teacher/courses': typeof appTeacherCoursesRouteWithChildren
  '/(app)/teacher/enrollments': typeof appTeacherEnrollmentsRoute
  '/(app)/teacher/reports': typeof appTeacherReportsRoute
  '/(app)/teacher/settings': typeof appTeacherSettingsRoute
  '/(app)/teacher/students': typeof appTeacherStudentsRoute
  '/(app)/teacher/support': typeof appTeacherSupportRoute
  '/(app)/courses/': typeof appCoursesIndexRoute
  '/(app)/student/': typeof appStudentIndexRoute
  '/(app)/teacher/': typeof appTeacherIndexRoute
  '/(app)/student/courses/$courseId': typeof appStudentCoursesCourseIdRoute
  '/(app)/student/feedback/$courseId': typeof appStudentFeedbackCourseIdRoute
  '/(app)/teacher/courses/$courseId': typeof appTeacherCoursesCourseIdRoute
  '/(app)/teacher/feedback/$courseId': typeof appTeacherFeedbackCourseIdRoute
  '/(app)/teacher/courses/': typeof appTeacherCoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/landing'
    | '/login'
    | '/student'
    | '/teacher'
    | '/courses'
    | '/courses/$courseId'
    | '/student/assignments'
    | '/student/enrollments'
    | '/student/grades'
    | '/student/messages'
    | '/student/resources'
    | '/student/schedule'
    | '/student/settings'
    | '/student/support'
    | '/teacher/calendar'
    | '/teacher/courses'
    | '/teacher/enrollments'
    | '/teacher/reports'
    | '/teacher/settings'
    | '/teacher/students'
    | '/teacher/support'
    | '/courses/'
    | '/student/'
    | '/teacher/'
    | '/student/courses/$courseId'
    | '/student/feedback/$courseId'
    | '/teacher/courses/$courseId'
    | '/teacher/feedback/$courseId'
    | '/teacher/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/landing'
    | '/login'
    | '/courses/$courseId'
    | '/student/assignments'
    | '/student/enrollments'
    | '/student/grades'
    | '/student/messages'
    | '/student/resources'
    | '/student/schedule'
    | '/student/settings'
    | '/student/support'
    | '/teacher/calendar'
    | '/teacher/enrollments'
    | '/teacher/reports'
    | '/teacher/settings'
    | '/teacher/students'
    | '/teacher/support'
    | '/courses'
    | '/student'
    | '/teacher'
    | '/student/courses/$courseId'
    | '/student/feedback/$courseId'
    | '/teacher/courses/$courseId'
    | '/teacher/feedback/$courseId'
    | '/teacher/courses'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/landing'
    | '/login'
    | '/(app)/student'
    | '/(app)/teacher'
    | '/(app)/courses'
    | '/(app)/courses/$courseId'
    | '/(app)/student/assignments'
    | '/(app)/student/enrollments'
    | '/(app)/student/grades'
    | '/(app)/student/messages'
    | '/(app)/student/resources'
    | '/(app)/student/schedule'
    | '/(app)/student/settings'
    | '/(app)/student/support'
    | '/(app)/teacher/calendar'
    | '/(app)/teacher/courses'
    | '/(app)/teacher/enrollments'
    | '/(app)/teacher/reports'
    | '/(app)/teacher/settings'
    | '/(app)/teacher/students'
    | '/(app)/teacher/support'
    | '/(app)/courses/'
    | '/(app)/student/'
    | '/(app)/teacher/'
    | '/(app)/student/courses/$courseId'
    | '/(app)/student/feedback/$courseId'
    | '/(app)/teacher/courses/$courseId'
    | '/(app)/teacher/feedback/$courseId'
    | '/(app)/teacher/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/courses': {
      id: '/(app)/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof appCoursesRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/teacher': {
      id: '/(app)/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof appTeacherRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/student': {
      id: '/(app)/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof appStudentRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/teacher/': {
      id: '/(app)/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof appTeacherIndexRouteImport
      parentRoute: typeof appTeacherRouteRoute
    }
    '/(app)/student/': {
      id: '/(app)/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof appStudentIndexRouteImport
      parentRoute: typeof appStudentRouteRoute
    }
    '/(app)/courses/': {
      id: '/(app)/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof appCoursesIndexRouteImport
      parentRoute: typeof appCoursesRoute
    }
    '/(app)/teacher/support': {
      id: '/(app)/teacher/support'
      path: '/support'
      fullPath: '/teacher/support'
      preLoaderRoute: typeof appTeacherSupportRouteImport
      parentRoute: typeof appTeacherRouteRoute
    }
    '/(app)/teacher/students': {
      id: '/(app)/teacher/students'
      path: '/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof appTeacherStudentsRouteImport
      parentRoute: typeof appTeacherRouteRoute
    }
    '/(app)/teacher/settings': {
      id: '/(app)/teacher/settings'
      path: '/settings'
      fullPath: '/teacher/settings'
      preLoaderRoute: typeof appTeacherSettingsRouteImport
      parentRoute: typeof appTeacherRouteRoute
    }
    '/(app)/teacher/reports': {
      id: '/(app)/teacher/reports'
      path: '/reports'
      fullPath: '/teacher/reports'
      preLoaderRoute: typeof appTeacherReportsRouteImport
      parentRoute: typeof appTeacherRouteRoute
    }
    '/(app)/teacher/enrollments': {
      id: '/(app)/teacher/enrollments'
      path: '/enrollments'
      fullPath: '/teacher/enrollments'
      preLoaderRoute: typeof appTeacherEnrollmentsRouteImport
      parentRoute: typeof appTeacherRouteRoute
    }
    '/(app)/teacher/courses': {
      id: '/(app)/teacher/courses'
      path: '/courses'
      fullPath: '/teacher/courses'
      preLoaderRoute: typeof appTeacherCoursesRouteImport
      parentRoute: typeof appTeacherRouteRoute
    }
    '/(app)/teacher/calendar': {
      id: '/(app)/teacher/calendar'
      path: '/calendar'
      fullPath: '/teacher/calendar'
      preLoaderRoute: typeof appTeacherCalendarRouteImport
      parentRoute: typeof appTeacherRouteRoute
    }
    '/(app)/student/support': {
      id: '/(app)/student/support'
      path: '/support'
      fullPath: '/student/support'
      preLoaderRoute: typeof appStudentSupportRouteImport
      parentRoute: typeof appStudentRouteRoute
    }
    '/(app)/student/settings': {
      id: '/(app)/student/settings'
      path: '/settings'
      fullPath: '/student/settings'
      preLoaderRoute: typeof appStudentSettingsRouteImport
      parentRoute: typeof appStudentRouteRoute
    }
    '/(app)/student/schedule': {
      id: '/(app)/student/schedule'
      path: '/schedule'
      fullPath: '/student/schedule'
      preLoaderRoute: typeof appStudentScheduleRouteImport
      parentRoute: typeof appStudentRouteRoute
    }
    '/(app)/student/resources': {
      id: '/(app)/student/resources'
      path: '/resources'
      fullPath: '/student/resources'
      preLoaderRoute: typeof appStudentResourcesRouteImport
      parentRoute: typeof appStudentRouteRoute
    }
    '/(app)/student/messages': {
      id: '/(app)/student/messages'
      path: '/messages'
      fullPath: '/student/messages'
      preLoaderRoute: typeof appStudentMessagesRouteImport
      parentRoute: typeof appStudentRouteRoute
    }
    '/(app)/student/grades': {
      id: '/(app)/student/grades'
      path: '/grades'
      fullPath: '/student/grades'
      preLoaderRoute: typeof appStudentGradesRouteImport
      parentRoute: typeof appStudentRouteRoute
    }
    '/(app)/student/enrollments': {
      id: '/(app)/student/enrollments'
      path: '/enrollments'
      fullPath: '/student/enrollments'
      preLoaderRoute: typeof appStudentEnrollmentsRouteImport
      parentRoute: typeof appStudentRouteRoute
    }
    '/(app)/student/assignments': {
      id: '/(app)/student/assignments'
      path: '/assignments'
      fullPath: '/student/assignments'
      preLoaderRoute: typeof appStudentAssignmentsRouteImport
      parentRoute: typeof appStudentRouteRoute
    }
    '/(app)/courses/$courseId': {
      id: '/(app)/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof appCoursesCourseIdRouteImport
      parentRoute: typeof appCoursesRoute
    }
    '/(app)/teacher/courses/': {
      id: '/(app)/teacher/courses/'
      path: '/'
      fullPath: '/teacher/courses/'
      preLoaderRoute: typeof appTeacherCoursesIndexRouteImport
      parentRoute: typeof appTeacherCoursesRoute
    }
    '/(app)/teacher/feedback/$courseId': {
      id: '/(app)/teacher/feedback/$courseId'
      path: '/feedback/$courseId'
      fullPath: '/teacher/feedback/$courseId'
      preLoaderRoute: typeof appTeacherFeedbackCourseIdRouteImport
      parentRoute: typeof appTeacherRouteRoute
    }
    '/(app)/teacher/courses/$courseId': {
      id: '/(app)/teacher/courses/$courseId'
      path: '/$courseId'
      fullPath: '/teacher/courses/$courseId'
      preLoaderRoute: typeof appTeacherCoursesCourseIdRouteImport
      parentRoute: typeof appTeacherCoursesRoute
    }
    '/(app)/student/feedback/$courseId': {
      id: '/(app)/student/feedback/$courseId'
      path: '/feedback/$courseId'
      fullPath: '/student/feedback/$courseId'
      preLoaderRoute: typeof appStudentFeedbackCourseIdRouteImport
      parentRoute: typeof appStudentRouteRoute
    }
    '/(app)/student/courses/$courseId': {
      id: '/(app)/student/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/student/courses/$courseId'
      preLoaderRoute: typeof appStudentCoursesCourseIdRouteImport
      parentRoute: typeof appStudentRouteRoute
    }
  }
}

interface appStudentRouteRouteChildren {
  appStudentAssignmentsRoute: typeof appStudentAssignmentsRoute
  appStudentEnrollmentsRoute: typeof appStudentEnrollmentsRoute
  appStudentGradesRoute: typeof appStudentGradesRoute
  appStudentMessagesRoute: typeof appStudentMessagesRoute
  appStudentResourcesRoute: typeof appStudentResourcesRoute
  appStudentScheduleRoute: typeof appStudentScheduleRoute
  appStudentSettingsRoute: typeof appStudentSettingsRoute
  appStudentSupportRoute: typeof appStudentSupportRoute
  appStudentIndexRoute: typeof appStudentIndexRoute
  appStudentCoursesCourseIdRoute: typeof appStudentCoursesCourseIdRoute
  appStudentFeedbackCourseIdRoute: typeof appStudentFeedbackCourseIdRoute
}

const appStudentRouteRouteChildren: appStudentRouteRouteChildren = {
  appStudentAssignmentsRoute: appStudentAssignmentsRoute,
  appStudentEnrollmentsRoute: appStudentEnrollmentsRoute,
  appStudentGradesRoute: appStudentGradesRoute,
  appStudentMessagesRoute: appStudentMessagesRoute,
  appStudentResourcesRoute: appStudentResourcesRoute,
  appStudentScheduleRoute: appStudentScheduleRoute,
  appStudentSettingsRoute: appStudentSettingsRoute,
  appStudentSupportRoute: appStudentSupportRoute,
  appStudentIndexRoute: appStudentIndexRoute,
  appStudentCoursesCourseIdRoute: appStudentCoursesCourseIdRoute,
  appStudentFeedbackCourseIdRoute: appStudentFeedbackCourseIdRoute,
}

const appStudentRouteRouteWithChildren = appStudentRouteRoute._addFileChildren(
  appStudentRouteRouteChildren,
)

interface appTeacherCoursesRouteChildren {
  appTeacherCoursesCourseIdRoute: typeof appTeacherCoursesCourseIdRoute
  appTeacherCoursesIndexRoute: typeof appTeacherCoursesIndexRoute
}

const appTeacherCoursesRouteChildren: appTeacherCoursesRouteChildren = {
  appTeacherCoursesCourseIdRoute: appTeacherCoursesCourseIdRoute,
  appTeacherCoursesIndexRoute: appTeacherCoursesIndexRoute,
}

const appTeacherCoursesRouteWithChildren =
  appTeacherCoursesRoute._addFileChildren(appTeacherCoursesRouteChildren)

interface appTeacherRouteRouteChildren {
  appTeacherCalendarRoute: typeof appTeacherCalendarRoute
  appTeacherCoursesRoute: typeof appTeacherCoursesRouteWithChildren
  appTeacherEnrollmentsRoute: typeof appTeacherEnrollmentsRoute
  appTeacherReportsRoute: typeof appTeacherReportsRoute
  appTeacherSettingsRoute: typeof appTeacherSettingsRoute
  appTeacherStudentsRoute: typeof appTeacherStudentsRoute
  appTeacherSupportRoute: typeof appTeacherSupportRoute
  appTeacherIndexRoute: typeof appTeacherIndexRoute
  appTeacherFeedbackCourseIdRoute: typeof appTeacherFeedbackCourseIdRoute
}

const appTeacherRouteRouteChildren: appTeacherRouteRouteChildren = {
  appTeacherCalendarRoute: appTeacherCalendarRoute,
  appTeacherCoursesRoute: appTeacherCoursesRouteWithChildren,
  appTeacherEnrollmentsRoute: appTeacherEnrollmentsRoute,
  appTeacherReportsRoute: appTeacherReportsRoute,
  appTeacherSettingsRoute: appTeacherSettingsRoute,
  appTeacherStudentsRoute: appTeacherStudentsRoute,
  appTeacherSupportRoute: appTeacherSupportRoute,
  appTeacherIndexRoute: appTeacherIndexRoute,
  appTeacherFeedbackCourseIdRoute: appTeacherFeedbackCourseIdRoute,
}

const appTeacherRouteRouteWithChildren = appTeacherRouteRoute._addFileChildren(
  appTeacherRouteRouteChildren,
)

interface appCoursesRouteChildren {
  appCoursesCourseIdRoute: typeof appCoursesCourseIdRoute
  appCoursesIndexRoute: typeof appCoursesIndexRoute
}

const appCoursesRouteChildren: appCoursesRouteChildren = {
  appCoursesCourseIdRoute: appCoursesCourseIdRoute,
  appCoursesIndexRoute: appCoursesIndexRoute,
}

const appCoursesRouteWithChildren = appCoursesRoute._addFileChildren(
  appCoursesRouteChildren,
)

interface appRouteRouteChildren {
  appStudentRouteRoute: typeof appStudentRouteRouteWithChildren
  appTeacherRouteRoute: typeof appTeacherRouteRouteWithChildren
  appCoursesRoute: typeof appCoursesRouteWithChildren
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appStudentRouteRoute: appStudentRouteRouteWithChildren,
  appTeacherRouteRoute: appTeacherRouteRouteWithChildren,
  appCoursesRoute: appCoursesRouteWithChildren,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
